import streamlit as st
import c2pa
import json
from io import BytesIO

# --- PAGE CONFIGURATION ---
st.set_page_config(
    page_title="Issi | AI Privacy Auditor",
    page_icon="icon.png",
    layout="centered"
)
st.markdown("""
                    <style>
                    [data-testid="column"] {
                        display: flex;
                        align-items: center;
                    }
                    [data-testid="stImage"] img {
                        border-radius: 0 !important;
                    }
                    h1 {
                        margin: 0 !important;
                        line-height: 1 !important;
                    }
                    </style>
            """, unsafe_allow_html=True)

# --- HEADER ---
# Create columns with tighter spacing for inline alignment
col1, col2 = st.columns([0.8, 9.2])
with col1:
    st.image("icon.png", width=50)    
with col2:
    st.markdown("# ISSI")

st.caption("AI Content Provenance & Privacy Auditor")
st.markdown("""
**Is your image leaking data?** Upload an image to inspect its **C2PA Content Credentials**.  
We audit for: `Gen-AI Signatures`, `Software Fingerprints` and `Hidden Ingredients`.
""")

# --- SIDEBAR (About You) ---
# --- SIDEBAR (About You) ---
with st.sidebar:
    st.header("By Chidinma Oham")
    st.markdown("AI Privacy Researcher & Developer Advocate.")
    st.markdown("[GitHub](https://github.com/TechEnginHER) | [LinkedIn](https://linkedin.com/in/WinifredOham)")
    
    # Custom "Grey Box" instead of blue st.info
    st.markdown("""
        <div style="background-color: #a3a5a89e; padding: 18px; border-radius: 8px; border: 4px dotted #a3a5a89e; font-size: 16px; color: #333;">
            This tool reverses the C2PA standard to reveal behavioral fingerprints in digital media.
        </div>
    """, unsafe_allow_html=True)
# --- THE AUDITOR ---
uploaded_file = st.file_uploader("Drop an image here...", type=['jpg', 'jpeg', 'png', 'webp'])

if uploaded_file is not None:
    # Save the uploaded file temporarily so C2PA can read it
    with open("temp_upload.jpg", "wb") as f:
        f.write(uploaded_file.getbuffer())

    st.divider()
    
    col1, col2 = st.columns([1, 2])
    with col1:
        st.image(uploaded_file, caption="Uploaded Media", use_container_width=True)

    with col2:
        st.subheader("Audit Report")
        
        try:
            # Run the Inspection
            reader = c2pa.Reader("temp_upload.jpg")
            manifest = json.loads(reader.json())
            
            # 1. STATUS
            st.success("Content Credentials Detected")
            
            # 2. ACTIVE MANIFEST
            active = manifest["manifests"][manifest["active_manifest"]]
            
            # 3. GENERATOR TOOL (The Privacy Leak)
            tool = active.get("claim_generator", "Unknown")
            st.markdown(f"**Generator Tool:** `{tool}`")
            
            if "Adobe" in tool:
                st.error("**Privacy Risk:** Adobe Software ID detected. High behavioral fingerprinting risk.")
            elif "OpenAI" in tool or "Microsoft" in tool:
                st.warning("**AI Detected:** Generated by a Synthetic Model.")
            
            # 4. INGREDIENTS (The Context Leak)
            ingredients = active.get("ingredients", [])
            if ingredients:
                st.warning(f"**{len(ingredients)} Source Ingredients Found**")
                for i, ing in enumerate(ingredients):
                    with st.expander(f"Source #{i+1}"):
                        st.json(ing)
            else:
                st.info("Single layer image (No external ingredients).")

            # 5. RAW DATA DOWNLOAD
            st.download_button(
                label="Download Full Forensic JSON",
                data=json.dumps(manifest, indent=2),
                file_name="provenance_report.json",
                mime="application/json"
            )

        except Exception as e:
            st.error("**No Credentials Found (Naked Image)**")
            st.markdown("""
            This image has no C2PA metadata. This could mean:
            - It was stripped by social media (X, Instagram).
            - It was created with non-compliant tools (Grok, older cameras).
            """)
