import sys
import json
import c2pa

def inspect_provenance(image_path):
    print(f"[*] Inspecting: {image_path}...")
    
    try:
        # 1. Read the C2PA Manifest
        # The reader extracts the cryptographic envelope embedded in the file
        reader = c2pa.Reader(image_path)
        manifest_json = reader.json()
        manifest_store = json.loads(manifest_json)
        
        # 2. Check if a Manifest exists
        if not manifest_store:
            print("[-] No Content Credentials found. This image is 'naked'.")
            return

        # 3. Extract Active Manifest (The most recent edit)
        active_label = manifest_store.get("active_manifest")
        if not active_label:
            print("[-] No active manifest found.")
            return
            
        active_data = manifest_store.get("manifests", {}).get(active_label)
        
        # 4. Security Audit: What is being leaked?
        print(f"\n[+] PROVENANCE FOUND: {active_label}")
        print(f"    - Title: {active_data.get('title', 'Unknown')}")
        print(f"    - Format: {active_data.get('format', 'Unknown')}")
        
        # Check for 'Ingredients' (Did they merge other photos?)
        # This is a major privacy risk: it reveals original filenames of assets used.
        ingredients = active_data.get("ingredients", [])
        if ingredients:
            print(f"\n[!] PRIVACY ALERT: {len(ingredients)} Source Images Detected")
            for ing in ingredients:
                title = ing.get('title', 'Untitled')
                fmt = ing.get('format', 'unknown')
                print(f"    - Source: {title} ({fmt})")
                print(f"      Relationship: {ing.get('relationship', 'componentOf')}")
        else:
            print("\n[i] No external ingredients detected (Single layer image).")

        # Check for Software Fingerprinting (What tools did they use?)
        # Reveals exact version numbers (e.g., 'Photoshop 25.1').
        claim = active_data.get("claim_generator", "Unknown")
        print(f"\n[i] Generator Tool: {claim}")
        
        if "Adobe" in claim:
            print("    -> RISK: High probability of Adobe ID linkage.")
        elif "OpenAI" in claim:
            print("    -> INFO: Generated by DALL-E/GPT model.")
        elif "C2PA" in claim:
            print("    -> INFO: Signed by standard C2PA tool.")

    except c2pa.Error.ManifestNotFound:
         print("[-] No Content Credentials found (C2PA signature missing).")
    except Exception as e:
        print(f"[!] Error processing file: {e}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python inspector.py <path_to_image>")
        print("Example: python inspector.py test_image.jpg")
    else:
        inspect_provenance(sys.argv[1])
